### PR TITLE
check if generations to be loaded exceed total generations available

### LINKED ISSUE #130: Clicking load more generations beyond block 0 fails
When we reach 0 we should not allow the user to see "load more..."

### PR DESCRIPTION
**Pull request by ror-shubham**
fixes #130

### CODE REVIEW

File: src/screens/generationList/generationList.vue [hunk 1]
```diff
@@ -102,8 +102,14 @@ export default {
...
-      this.numGenerations += 10
-      await this.$store.dispatch('blocks/getLatestGenerations', Object.keys(this.generations).length + 10)
+      if (this.height - this.numGenerations >= 10) {
+        this.numGenerations += 10
+        await this.$store.dispatch('blocks/getLatestGenerations', Object.keys(this.generations).length + 10)
+      } else if (this.height > this.numGenerations) {
+        let toAdd = this.height - this.numGenerations
+        this.numGenerations += toAdd
+        await this.$store.dispatch('blocks/getLatestGenerations', Object.keys(this.generations).length + toAdd)
+      }
```
Comment (davidyuk) [inline src/screens/generationList/generationList.vue]: `if` is not necessary:
```js
const toAdd = Math.min(this.height - this.numGenerations, 10, 0)
this.numGenerations += toAdd
await this.$store.dispatch('blocks/getLatestGenerations', Object.keys(this.generations).length + toAdd)
```

File: src/screens/generationList/generationList.vue [hunk 2]
```diff
@@ -102,14 +102,9 @@ export default {
...
       this.isLoadingMore = true
-      if (this.height - this.numGenerations >= 10) {
-        this.numGenerations += 10
-        await this.$store.dispatch('blocks/getLatestGenerations', Object.keys(this.generations).length + 10)
-      } else if (this.height > this.numGenerations) {
-        let toAdd = this.height - this.numGenerations
-        this.numGenerations += toAdd
-        await this.$store.dispatch('blocks/getLatestGenerations', Object.keys(this.generations).length + toAdd)
-      }
+      const toAdd = Math.min(this.height - this.numGenerations, 10)
```
Comment (davidyuk) [inline src/screens/generationList/generationList.vue]: can `this.height - this.numGenerations` be negative? looks I was wrong and `Math.max(Math.min(this.height - this.numGenerations, 10), 0)` should be used in this case.
